### ISSUE TITLE
API for wiping index

### ISSUE THREAD

**Issue by rymohr** [cshum/levi#11]
Is there any API for resetting the index and starting over from scratch?

**Comment by cshum** [comment]
If you want to clear the database you can simply delete the database folder.

If you want to rebuild an index while keeping the document, 
you can currently do 
```js
lv.reindex(key, [callback])
```
However I am still figuring out a better way to expose this, so it is subject to change.

**Comment by rymohr** [comment]
Thanks, what about in the browser?

**Comment by cshum** [comment]
The browser part is based on https://github.com/maxogden/level.js
To delete database you can do 
```js
require('level-js').destroy('./test/db', function () { ... })
```

**Comment by rymohr** [comment]
A simple `levi(path).reset()` or `levi(path).clear()` would be nice. Open to a PR?

**Comment by cshum** [comment]
The reason for not making `destroy()` a method, is because the `levi(path)` instance is not usable after being destroyed. 
So `destroy()` would better be a function on its own. See  [`leveldown.destory()`](https://github.com/Level/levelup#leveldowndestroylocation-callback)

Another problem, not every [LevelDOWN database adapter](https://github.com/Level/abstract-leveldown) supports `destroy()` function as it is not part of the spec. So this method may not work consistently across every backends.

However Levi uses [LevelDOWN](https://github.com/Level/leveldown) and [level.js](https://github.com/maxogden/level.js) by default and they both have `destroy()` function. 
I do agree `levi.destroy(path, cb)` would be a convenient addition.

**Comment by rymohr** [comment]
@cshum thanks for the quick addition!
